experiment_prefix = "portfolio_toolkit"
tracking_uri = "https://adams-macbook-pro.tail5ddc35.ts.net"
backend_store_uri = "sqlite:///mlflow/mlflow.db"
artifact_root = "mlflow/artifacts"
host = "127.0.0.1"
port = 5000
